# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('camis', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('cuisine_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('inspection_date', models.DateField()),
                ('inspection_type', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('violation_code', models.CharField(max_length=3)),
                ('violation_description', models.TextField()),
                ('critical_flag', models.CharField(choices=[('Critical', 'Critical'), ('Not Critical', 'Not Critical'), ('N/A', 'Not Applicable')], max_length=12)),
                ('score', models.SmallIntegerField(null=True)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('N', 'Not Yet Graded'), ('P', 'Grade Pending issued on re-opening following an initial inspection that resulted in a closure'), ('Z', 'Grade Pending')], max_length=1)),
                ('grade_date', models.DateField(null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Business')),
            ],
        ),
    ]
