# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-20 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='critical_flag',
            field=models.CharField(choices=[('Critical', 'Critical'), ('Not Critical', 'Not Critical'), ('Not Applicable', 'Not Applicable')], max_length=64),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('Not Yet Graded', 'Not Yet Graded'), ('P', 'Grade Pending issued on re-opening following an initial inspection that resulted in a closure'), ('Z', 'Grade Pending')], max_length=64),
        ),
    ]
